name: MCMEPVP
main: at.doebi.MCMEPVP
version: 1.0.0
commands:
   pvp:
      description: PVP
      usage: /<command> [join|leave|class]
   shout:
      description: Shout a message to Everyone!
      usage: /<command> [msg]
   pa:
      description: PVP Admin
      usage: /<command> [start|set]
      permission: mcmepvp.admin
      permission-message: You're not an Admin!