name: MCMEPVP
main: at.doebi.MCMEPVP
version: 1.0.0
commands:
   pvp:
      description: PVP
      usage: /<command> [join|leave|class]
      permission: mcmepvp.player
      permission-message: FUCK OFF!
   shout:
      description: Shout a message to Everyone!
      usage: /<command> [msg]
      permission: mcmepvp.player
      permission-message: FUCK OFF!
   pa:
      description: PVP Admin
      usage: /<command> [start]
      permission: mcmepvp.admin
      permission-message: FUCK OFF!